name: "Personal Page CI"
on: [push, pull_request]

jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 16
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
    
      - name: Install dependencies
        run:  cd personal-page-app && npm install
      - name: Run tests
        run: cd personal-page-app && npm run test
        
